In [1]:
import pandas as pd
import re
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from collections import Counter

In [3]:
who_AMRO = pd.read_csv('../data/who_AMRO.csv')

In [17]:
who_AMRO

,ContaminationIndividualID,FoodID,CountryName,FoodEx2Code,FoodName,FoodGroupID,FoodGroupName,GEMSFoodName,CountryID,RegionCode,ContaminantID,ContaminantName,SerialNumber,UnitID,UnitName,ResultValue,Year,WHO_Food_Code
0,25615,372,Canada,A03MA,Beer and beer-like beverage,15,Alcoholic beverages,Beer and beer-like beverage,60,AMR,3,Aflatoxin B1,451,3,ug/kg,0.0,2000,14.2.1
1,25616,372,Canada,A03MA,Beer and beer-like beverage,15,Alcoholic beverages,Beer and beer-like beverage,60,AMR,3,Aflatoxin B1,452,3,ug/kg,0.0,2000,14.2.1
2,25617,372,Canada,A03MA,Beer and beer-like beverage,15,Alcoholic beverages,Beer and beer-like beverage,60,AMR,3,Aflatoxin B1,453,3,ug/kg,0.0,2000,14.2.1
3,25618,372,Canada,A03MA,Beer and beer-like beverage,15,Alcoholic beverages,Beer and beer-like beverage,60,AMR,3,Aflatoxin B1,454,3,ug/kg,0.0,2000,14.2.1
4,25619,372,Canada,A03MA,Beer and beer-like beverage,15,Alcoholic beverages,Beer and beer-like beverage,60,AMR,3,Aflatoxin B1,455,3,ug/kg,0.0,2000,14.2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260597,9039086,70336,Brazil,A001D,"Rice, Husked",1,Cereals and cereal-based products,"Rice, Husked",48,AMR,2,Aflatoxin (total),FI-4123/14,2,ug/kg,0.0,2014,CM 0649
3260598,9039087,70336,Brazil,A001D,"Rice, Husked",1,Cereals and cereal-based products,"Rice, Husked",48,AMR,2,Aflatoxin (total),FI-4514/14,2,ug/kg,0.0,2014,CM 0649
3260599,9039088,70336,Brazil,A001D,"Rice, Husked",1,Cereals and cereal-based products,"Rice, Husked",48,AMR,2,Aflatoxin (total),FI-4616/14,2,ug/kg,0.0,2014,CM 0649
3260600,9039089,70336,Brazil,A001D,"Rice, Husked",1,Cereals and cereal-based products,"Rice, Husked",48,AMR,2,Aflatoxin (total),FI-4630/14,2,ug/kg,0.0,2014,CM 0649
3260601,9039090,70336,Brazil,A001D,"Rice, Husked",1,Cereals and cereal-based products,"Rice, Husked",48,AMR,2,Aflatoxin (total),FI-4925/14,2,ug/kg,0.0,2014,CM 0649

In [11]:
canada_who = who_AMRO[['ContaminationIndividualID', 
                       'FoodName', 
                       'FoodGroupName', 
                       'ContaminantName', 
                       'Year']].loc[who_AMRO['CountryName'] == 'Canada']

In [12]:
us_who = who_AMRO[['ContaminationIndividualID', 
                       'FoodName', 
                       'FoodGroupName', 
                       'ContaminantName', 
                       'Year']].loc[who_AMRO['CountryName'] == 'United States of America']

In [8]:
who_AMRO.groupby('CountryName').count()

,ContaminationIndividualID,FoodID,FoodEx2Code,FoodName,FoodGroupID,FoodGroupName,GEMSFoodName,CountryID,RegionCode,ContaminantID,ContaminantName,SerialNumber,UnitID,UnitName,ResultValue,Year,WHO_Food_Code
CountryName,,,,,,,,,,,,,,,,,
Brazil,426633,426633,426633,426633,426633,426633,426633,426633,426633,426633,426633,21923,426633,426633,426632,426633,426633
Canada,2249435,2249435,2249435,2249435,2249435,2249435,2249435,2249435,2249435,2249435,2249435,2234281,2249435,2249435,2249101,2249435,2249435
Chile,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156
Colombia,143,143,143,143,143,143,143,143,143,143,143,143,143,143,143,143,143
Cuba,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78
Ecuador,263,263,263,263,263,263,263,263,263,263,263,0,263,263,263,263,263
United States of America,583859,583859,583859,583859,583859,583859,583859,583859,583859,583859,583859,536042,583859,583859,583853,583859,583859
Uruguay,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35

In [15]:
canada_who.groupby(['FoodGroupName', 'Year', 'ContaminantName']).count()

                                                                         ContaminationIndividualID  \
FoodGroupName                                      Year ContaminantName
Alcoholic beverages                                1998 Aflatoxin B1                            68
                                                        Aflatoxin B2                            68
                                                        Aflatoxin G1                            68
                                                        Aflatoxin G2                            68
                                                   1999 Aflatoxin B1                            36
...                                                                                            ...
Vegetables and vegetable products (including fu... 2017 Tolfenpyrad                            105
                                                        Triadimenol                            160
                                                        Triazophos                             160
                                                        Triflumizole                           160
                                                        Triforine                              160

                                                                         FoodName
FoodGroupName                                      Year ContaminantName
Alcoholic beverages                                1998 Aflatoxin B1           68
                                                        Aflatoxin B2           68
                                                        Aflatoxin G1           68
                                                        Aflatoxin G2           68
                                                   1999 Aflatoxin B1           36
...                                                                           ...
Vegetables and vegetable products (including fu... 2017 Tolfenpyrad           105
                                                        Triadimenol           160
                                                        Triazophos            160
                                                        Triflumizole          160
                                                        Triforine             160

[5832 rows x 2 columns]

In [16]:
us_who.groupby(['FoodGroupName', 'Year', 'ContaminantName']).count()

                                                                         ContaminationIndividualID  \
FoodGroupName                                      Year ContaminantName
Alcoholic beverages                                2000 Lead                                    14
                                                   2001 Lead                                    12
                                                   2002 Lead                                    12
                                                   2003 Cadmium                                  8
                                                        Copper                                   8
...                                                                                            ...
Vegetables and vegetable products (including fu... 2015 Tebuconazole                          1997
                                                        Thiamethoxam                          3075
                                                        Triadimenol                            378
                                                        Triflumizole                           378
                                                   2017 Lead                                    22

                                                                         FoodName
FoodGroupName                                      Year ContaminantName
Alcoholic beverages                                2000 Lead                   14
                                                   2001 Lead                   12
                                                   2002 Lead                   12
                                                   2003 Cadmium                 8
                                                        Copper                  8
...                                                                           ...
Vegetables and vegetable products (including fu... 2015 Tebuconazole         1997
                                                        Thiamethoxam         3075
                                                        Triadimenol           378
                                                        Triflumizole          378
                                                   2017 Lead                   22

[1336 rows x 2 columns]